# Generated by Django 3.1.5 on 2021-01-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='relator',
            new_name='realtor',
        ),
    ]
