# Generated by Django 3.1.5 on 2021-01-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210107_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqfr',
            new_name='sqft',
        ),
    ]
